# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_crc24q <- function(data, len) {
    .Call(`_rRTCM3_calculate_crc24q`, data, len)
}

checkMessage <- function(msg) {
    .Call(`_rRTCM3_checkMessage`, msg)
}

rtcmCut <- function(msg, from = 0L, to = NA_integer_, display_progress = TRUE) {
    .Call(`_rRTCM3_rtcmCut`, msg, from, to, display_progress)
}

rtcmGetMsgNumber <- function(msg) {
    .Call(`_rRTCM3_rtcmGetMsgNumber`, msg)
}

rtcmMsmDecodeHeader <- function(msg) {
    .Call(`_rRTCM3_rtcmMsmDecodeHeader`, msg)
}

rtcmDecodeSatMsm7 <- function(msg, header = NULL) {
    .Call(`_rRTCM3_rtcmDecodeSatMsm7`, msg, header)
}

rtcmDecodeSigMsm7 <- function(msg, header = NULL) {
    .Call(`_rRTCM3_rtcmDecodeSigMsm7`, msg, header)
}

